project:
  type: website
  output-dir: docs

website:
  title: "Philly Emerging Water Contaminants Initiative"
  navbar:
    left:
      - href: index.qmd
        text: Preliminary Maps
      - href: static_POIs.qmd
        text: POI Sampling Maps

format:
  html:
    theme: lux
    toc: true
    code-fold: true

execute:
  freeze: auto